### ISSUE TITLE
release versions missing for registered releases

### ISSUE THREAD

**Issue by andreasvoigt** [jsdevtom/truegin#7]
At the NPM registry following releases are registered:

- 4.1.0
- 4.0.2
- 4.0.1
- 4.0.0
- 3.0.0
- 2.3.2
- 2.3.1

https://www.npmjs.com/package/truegin

But the releases 4.1.0 and 4.0.2 are missing in this project.

**Comment by jsdevtom** [comment]
Hi @andreasvoigt ! Thanks for pointing this out :tada: . The missing releases have been published
